language: c++

services: docker

os: linux

env:
  global:
    - SHARED_DIR=/home/shared
  matrix:
    - NAME=g++-8 COMMAND="docker run --rm -ti -e COVERALLS_TOKEN -v ${TRAVIS_BUILD_DIR}:${SHARED_DIR} -w ${SHARED_DIR} cequenser/sequencer-ci-linux ${SHARED_DIR}/scripts/run_tests.sh g++-8 gcov-8"
    - NAME=clang++-8 COMMAND="docker run --rm -ti -e COVERALLS_TOKEN -v ${TRAVIS_BUILD_DIR}:${SHARED_DIR} -w ${SHARED_DIR} cequenser/sequencer-ci-linux ${SHARED_DIR}/scripts/run_tests.sh clang++-8"
     
install:
  - docker pull cequenser/sequencer-ci-linux:latest

script:
  - $COMMAND

