version: '3.3'

services:
  jenkins:
    image: cequenser/sequencer-ci-jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    user: "1002"


  jenkins-slave:
    image: cequenser/sequencer-ci-jenkins-slave
    restart: always
    volumes:
      - jenkins_slave_ssh:/home/jenkins/.ssh
    depends_on:
      - jenkins


volumes:
  jenkins-data:
    external: true
  jenkins_slave_ssh:
    external: true
